### ISSUE TITLE
"links" force causes errors if link data is transformed from Formula

### ISSUE THREAD

**Issue by boxfish** [uwdata/vega-force#2]
If the links data used in `links` force is from an upstream Formula transform, the following line [(L89)](https://github.com/vega/vega-force/blob/master/src/Force.js#L89) will throw error. The reason being that the `value` of the link source (in this case the Formula transform) was `null`, which later was consumed by update.js inside dataflow [(L68)](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/update.js#L68), and eventually throw error from Changeset [(L93)](https://github.com/vega/vega-dataflow/blob/master/src/ChangeSet.js#L93) because the tuples are `null` and as a result the `slice` function is not available.

Attached is a simple spec that will reproduce the issue. There is a workaround by appending a `Collect` transform after the `Formula`, but would like to call it out here for clean fix.

        {
          "$schema": "https://vega.github.io/schema/vega/v3.0.json",
          "width": 700,
          "height": 500,
          "padding": 0,
          "autosize": "none",
          "signals": [
            {
              "name": "cx",
              "update": "width / 2"
            },
            {
              "name": "cy",
              "update": "height / 2"
            }
          ],
          "data": [
            {
              "name": "node-data",
              "values": [
                {
                  "name": "A"
                },
                {
                  "name": "B"
                },
                {
                  "name": "C"
                },
                {
                  "name": "D"
                },
                {
                  "name": "E"
                },
                {
                  "name": "F"
                },
                {
                  "name": "G"
                }
              ]
            },
            {
              "name": "link-data",
              "values": [
                {
                  "from": 1,
                  "to": 0
                },
                {
                  "from": 2,
                  "to": 0
                },
                {
                  "from": 3,
                  "to": 0
                },
                {
                  "from": 4,
                  "to": 1
                },
                {
                  "from": 2,
                  "to": 3
                },
                {
                  "from": 5,
                  "to": 2
                },
                {
                  "from": 6,
                  "to": 4
                }
              ],
              "transform": [{
                "type": "formula",
                "as": "source",
                "expr": "datum.from"
              }, {
                "type": "formula",
                "as": "target",
                "expr": "datum.to"
              }]
            }
          ],
          "marks": [
            {
              "name": "nodes",
              "type": "symbol",
              "zindex": 1,
              "from": {
                "data": "node-data"
              },
              "encode": {
                "enter": {
                  "fill": {
                    "value": "blue"
                  },
                  "stroke": {
                    "value": "white"
                  }
                },
                "update": {
                  "size": {
                    "value": 400
                  },
                  "cursor": {
                    "value": "pointer"
                  }
                }
              },
              "transform": [
                {
                  "type": "force",
                  "iterations": 300,
                  "forces": [
                    {
                      "force": "center",
                      "x": {
                        "signal": "cx"
                      },
                      "y": {
                        "signal": "cy"
                      }
                    },
                    {
                      "force": "collide",
                      "radius": 30
                    },
                    {
                      "force": "link",
                      "links": "link-data"
                    }
                  ]
                }
              ]
            },
            {
              "type": "path",
              "from": {
                "data": "link-data"
              },
              "interactive": false,
              "encode": {
                "update": {
                  "stroke": {
                    "value": "#ccc"
                  },
                  "strokeWidth": {
                    "value": 0.5
                  }
                }
              },
              "transform": [
                {
                  "type": "linkpath",
                  "shape": "line",
                  "sourceX": "datum.source.x",
                  "sourceY": "datum.source.y",
                  "targetX": "datum.target.x",
                  "targetY": "datum.target.y"
                }
              ]
            }
          ]
        }

**Comment by jheer** [comment]
Thanks! I updated vega-dataflow to use the `pulse.source` array rather than the operator `value` when performing a `pulse` operation. This fixes the error observed here, and will be included in the next vega-dataflow and vega releases.
